### ISSUE TITLE
match interfaces

### ISSUE THREAD

**Issue by Thomas-Ulrich** [SeisSol/SeisSolXDMF.jl#1]
Hi,
I wonder if you are aware of the python equivalent of seissolXDMF.jl
https://github.com/SeisSol/Visualization/tree/master/seissolxmdf
And I wonder it would not be better to unify the interface of both readers (that is change the interface of this one to match the python reader ;-) ).

**Comment by krenzland** [comment]
Hi,
the short version is yes and no ;)

Long answer:
Yes, we are aware of the python equivalent but it does not make sense to use the same interface. Julia is just not an object-oriented language, i.e., it's impossible to have the same interface (and emulating it would be very much non-idiomatic).

Right now it's only used in https://github.com/SeisSol/SAMPLER, in the future we might also want to use it in other scripts. Maybe we'll change the interface then - but not to a similar one as the Python version.
